### ISSUE TITLE
[QA] "View on Wormholescan" search is not found

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1150]
Preconditions:
Fin wallet connected at sending From section
Metamask wallet connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Tested from: https://wormhole-connect.netlify.app/

Steps:
1. Prepare to send 0.01 SEI from Sei to Goerli
2. Click Approve and proceed with transaction
3. While transaction is in progress click on Sei explorer
4. Observe (Issue reported here - https://github.com/wormhole-foundation/wormhole-connect/issues/671 )
5. Close Sei explorer
6. Click on "View on Wormhole explorer"
7. Observe

Actual result: For transactions from Sei, Sei explorer link can not be found and "View on Wormhole explorer" search can not be found

Expected result: "View on Wormhole explorer" link locates the correct transaction from Sei

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/49bca842-2ad4-44ea-a004-21e4e01dbccd

**Comment by AigaD** [comment]
Checked on https://deploy-preview-1174--wormhole-connect.netlify.app/ [Testnet] with macOS 12.7 and Google Chrome Version 119.0.6045.123 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.01 SEI from Sei (Leap) to Solana (Phantom)
2. Click "Approve and proceed with transaction" button
3. Click "View on Wormhole Explorer" link on Redeem screen

Link to [Wormhole scan](https://wormholescan.io/#/tx/32/9328673cb5de3fd99974cefbbd90fea033f4c59a572abfd7e1a4eebcc5d18157/23095?network=TESTNET)

Attachment:
![Screenshot 2023-11-15 at 12 12 38](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/75b3e3aa-bece-4c52-a48e-77a673167b34)

**Comment by AigaD** [comment]
Issue reproducible from: https://deploy-preview-1174--wormhole-connect.netlify.app/#
For transaction from Optimism Goerli to Arbitrum Goerli, when clicking on Wormholescan, result shows - " Search not found"
[Optimism Goerli](https://goerli-optimism.etherscan.io/tx/0x6078bdf2ed865bc4e497db538e22c08d3bbc8aa229e66e7afd8b1ac0d347c25b)
[Wormholescan](https://wormholescan.io/#/tx/0x6078bdf2ed865bc4e497db538e22c08d3bbc8aa229e66e7afd8b1ac0d347c25b?network=TESTNET)

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b238a583-d3f2-4067-9187-8af09a277940

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/df5df83982/#
For transaction [Arbitrum](https://arbiscan.io/tx/0x74348a6a8bb25ba4dadc0456061a3d2481ba1c9cbd5f00a71f54cee127a92157) -> Base, [Wormhole scan](https://wormholescan.io/#/tx/0x74348a6a8bb25ba4dadc0456061a3d2481ba1c9cbd5f00a71f54cee127a92157) search is not found

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5dd06cde-95ad-4253-ba75-57606d167121

![Screenshot 2023-11-23 at 14 59 29](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b4b57ed3-03ce-46dc-97e4-7979ef3a8728)

**Comment by AigaD** [comment]
Same reproduced for USDC transaction from [Ethereum](https://etherscan.io/tx/0x69c3e96265119e52b2aabb7fa3c303cbded4b5d76a5dd294f9be3365d99c0968) to Avalanche, link to [Wormhole](https://wormholescan.io/#/tx/0x69c3e96265119e52b2aabb7fa3c303cbded4b5d76a5dd294f9be3365d99c0968) scan shows Search not found
Tested from: https://preview.portalbridge.com/df5df83982/usdc-bridge/

**Comment by AigaD** [comment]
Reproduced also from Testnet: https://testnet.portalbridge.com/df5df83982/usdc-bridge/
For transaction [Goerli ](https://goerli.etherscan.io/tx/0xbdb485832c2960b6113a98a29726d764373806723a0aad87988ffe23297b3999)-> [Fuji](https://testnet.avascan.info/blockchain/c/tx/0xfb95858106abc792eeccf65d51a388de81a32f50977bd6e36e8a4729fd3ba1df), Wormhole scan returns Search not found

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1312--wormhole-connect-mainnet.netlify.app/#
For transaction USDC from [Polygon](https://polygonscan.com/tx/0x02fefcfa44f851647087f757a6f6e2a7000e8a161cc9fd86c2fe437e675a1ed2) to Arbitrum
[Wormholescan](https://wormholescan.io/#/tx/0x02fefcfa44f851647087f757a6f6e2a7000e8a161cc9fd86c2fe437e675a1ed2) link
Attachment:
![Screenshot 2023-12-15 at 09 20 00](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/cb36c4eb-1317-4140-90b2-583ac23a30dd)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
For transaction USDC from Sei to Mumbai, [Wormholescan](https://wormholescan.io/#/tx/21/40440411a170b4842ae7dee4f4a7b7a58bc0a98566e998850a7bb87bf5dc05b9/223?network=TESTNET) search is not found.
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/83f248e3-8ee9-4bac-a3b1-45013ed60a12

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
For transaction WMATIC from Sepolia to Fuji, search on [Wormholescan](https://wormholescan.io/#/tx/0xe5ae47057d9a6205faa321b685589b46e0ecacb614c0a63dfdc89a3aea16fa66?network=TESTNET) is not found
Attachment:

![Screenshot 2024-02-13 at 11 16 45](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/fa7fa28e-d2b1-4fe0-b1e9-290b53fe606a)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending WSOL from Solana (Phantom) to Fuji (MetaMask). "View on Wormholescan" search is not found: [Wormholescan](https://wormholescan.io/#/tx/1/3b26409f8aaded3f5ddca184695aa6a0fa829b0c85caf84856324896d214ca98/27635?network=TESTNET). Send from tx: [Solana Explorer](https://explorer.solana.com/tx/56BZNJDcon7wTJWumzssNi9QVyLe1YCPdAhPYVdtxHbMv2UEHEjsZTvqXaroYPnDzbkJwPS1L1xwNiD23yrtVSwT?cluster=devnet).


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/7a6a6663-9ab9-4a1f-95db-38dbe7d00370)

**Comment by AigaD** [comment]
Tested from: https://portalbridge.com/#
For transaction CELO from [Kujira](https://finder.kujira.network/kaiyo-1/tx/F94FBA5174D160C5C400F5F423A5EC7B2CEA81095CC3DEF7094ACF855A3C926D) (Leap) to [Arbitrum](https://arbiscan.io/tx/0xe42b64eba9b02b6454ceb7ae5c8caf4c0bb1819a017155f412804152421a8b13) (Metamask) [View on Wormholescan](https://wormholescan.io/#/tx/3104/aeb534c45c3049d380b9d9b966f9895f53abd4301bfaff407fa09dea8ae7a924/26300) search is not found

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5af6c45d-4988-4673-adee-c0adbc031f89

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/b1ba6e856a/#
[Wormholescan](https://wormholescan.io/#/tx/3104/aeb534c45c3049d380b9d9b966f9895f53abd4301bfaff407fa09dea8ae7a924/27043)
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/46e3f30f-3544-4f07-9719-cdda66252fff

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/b05f4e9322/
Search not found result shows in [Wormholescan](https://wormholescan.io/#/tx/3104/aeb534c45c3049d380b9d9b966f9895f53abd4301bfaff407fa09dea8ae7a924/27835) for transaction 0.001 WMATIC from Evmos to BSC

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/493d2ea0-085d-4267-8e58-52a5b54dda99

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/bceadc8c64/#
For transaction W asset from Ethereum to Base Wormholescan search is not found
Attachment:
[Wormholescan](https://wormholescan.io/#/tx/0xca5f386a5504019d388b1a46b51c11781b7288310d55022b79a0dc3d3d47b982)
<img width="1139" alt="Screenshot 2024-05-09 at 11 52 08" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/461106e7-dbb0-4f36-8a4e-b7e91c210452">

**Comment by tsadovska** [comment]
Rechecked scenarios mentioned in the ticket. Some scenarios are no longer reproducible, because the Goerli network is deprecated.
Remaining issues: 

- Transactions from Sei are stuck on Step 2, ticket https://github.com/wormhole-foundation/wormhole-connect/issues/762
- Transactions from Polygon fails to start, ticket https://github.com/wormhole-foundation/wormhole-connect/issues/2231 


Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet] with following scenarios:

- WGLMR transfer from [Sepolia](https://sepolia.etherscan.io/tx/0xfd8302cb9263044a44a02a06904ef7a7b028dbe4bd83516336f23f450f013148) (MetaMask) to [Fuji](https://testnet.avascan.info/blockchain/c/tx/0xd6b0fc422ac4a8ae08f4018ef6a227af5056f7de01c8eb655c3f063db81380eb) (MetaMask)), link to [Wormholescan](https://wormholescan.io/#/tx/0xfd8302cb9263044a44a02a06904ef7a7b028dbe4bd83516336f23f450f013148?network=TESTNET)
- WSOL transfer from [Solana](https://explorer.solana.com/tx/4iQQsgrV2XbrDBXvLXrwXRkvWpKcRiXfK49zDxbRLyg6Zd487iE8prQERURZy6Rdc2AV6ioUS6AdytdDQS6YjNb1?cluster=devnet) (Phantom) to [Fuji](https://testnet.avascan.info/blockchain/c/tx/0x0b914a8de12cb4d9bbafb7d4b7301a1f4381777395bc827106b86cb575a2697a) (MetaMask), link to [Wormholescan](https://wormholescan.io/#/tx/1/3b26409f8aaded3f5ddca184695aa6a0fa829b0c85caf84856324896d214ca98/28602?network=TESTNET) 

Issue is no longer reproducible on https://portalbridge.com/ [Mainnet] with following scenarios:

- CELO transfer from [Kujira](https://finder.kujira.network/kaiyo-1/tx/FA6DB306F2E1ECE7A8CD4E11B838E3409EA8894D4607123951673EF5AF90A994) (Leap) to [Arbitrum](https://arbiscan.io/tx/0x384e27b5c6e79d8d3f93d5fe530e4a56aea148119ba63fff7d389fa95f829952) (MetaMask), link to [Wormholescan](https://wormholescan.io/#/tx/3104/aeb534c45c3049d380b9d9b966f9895f53abd4301bfaff407fa09dea8ae7a924/38857)
- WAVAX transfer from [Injective](https://explorer.injective.network/transaction/A51B6B271E37B768633155FEB3443257DAE0C087DAAB8C09C2E7DEEB71598AB9/) (Leap) to [Optimism](https://optimistic.etherscan.io/tx/0xaab0cf32cd13d469b5a67e6a0c0adc7884ef9f31f697a0b5cb6a49cd3e942ea0) (MetaMask), link to [Wormholescan](https://wormholescan.io/#/tx/3104/aeb534c45c3049d380b9d9b966f9895f53abd4301bfaff407fa09dea8ae7a924/38865)
- CELO transfer from [Evmos](https://www.mintscan.io/evmos/tx/8A6A9CC28E09A28E52176C5170E1A7322FDB22BDEFEBE036B67692BF933A537B) (Leap) to [BSC](https://bscscan.com/tx/0x6824c5478fea8bcf2f8235b5cf3bb1572d6e62852e088182519188f9d7eaa32c) (MetaMask), link to [Wormholescan](https://wormholescan.io/#/tx/3104/aeb534c45c3049d380b9d9b966f9895f53abd4301bfaff407fa09dea8ae7a924/38866)
- W  transfer from [Ethereum](https://etherscan.io/tx/0x18169c9559f06011a0f5d8d23c7cb9cdfceba9e61d4c92d11525232f66756d27) (MetaMask) to [Base](https://basescan.org/tx/0x01ba1b1f3959bafa4c860a387bf94ba9ac46937cb7670b065dd5aa7bf589d326) (MetaMask), link to [Wormholescan](https://wormholescan.io/#/tx/0x18169c9559f06011a0f5d8d23c7cb9cdfceba9e61d4c92d11525232f66756d27)

Ticket is closed.
