### ISSUE TITLE
[QA] [Testnet, Mainnet] Cannot register asset for transaction to Evmos/ Kujira/ Cosmoshub/ Osmosis

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1238]
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 12.7 and Google Chrome Version 119.0.6045.159 (Official Build) (x86_64).

Steps:
1. Prepare to send 0.01 SEI from Sei (Leap) to Evmos/ Kujira/ Cosmoshub/ Osmosis (Leap)
2. Click on [register](https://wormhole-foundation.github.io/example-token-bridge-ui/#/register) link on warning "This token is not registered..."
3. Select Sei network as source chain
4. Select SEI asset
5. Open Networks list in Step 2 and check if Evmos/ Kujira/ Cosmoshub/ Osmosis chain is in the list

Evmos, Kujira, Cosmoshub, Osmosis chains are not present in the Networks list

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/5767b6ff-877c-44a8-9239-12f073dc6918)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/8842caf4-6432-4e3d-8246-bc7fc15d275e)

## What is the expected/desired behavior
Evmos, Kujira, Cosmoshub, Osmosis chains are present in the Networks list.

**Comment by AigaD** [comment]
Reproduced from Mainnet: https://wormhole-connect-mainnet.netlify.app/#
Cannot register tBTC asset for transaction Optimism to Evmos, because Evmos Network is not present in the Network drop down list https://portalbridge.com/advanced-tools/#/register
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/fe52dd09-0fb3-46e9-a2ca-01e7e012de55

**Comment by nik-suri** [comment]
We need to add asset registration for chains connected to Wormhole Gateway.

Assets only need to be attested once, then they'll work for all chains connected to Gateway.

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/# and https://wormhole-foundation.github.io/example-token-bridge-ui/#/register
Cannot register USDC (Arbitrum) asset for transaction Cosmoshub to Optimism Goerli, becauce Cosmoshub network is not shown in available network list at [register](https://wormhole-foundation.github.io/example-token-bridge-ui/#/register) page
Attachment:


![Screenshot 2024-02-29 at 12 48 34](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4dfb0ce8-1a46-46e4-8a8e-8dfe24fb8afa)

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/b05f4e9322/ and https://portalbridge.com/ / https://portalbridge.com/advanced-tools/#/register
Cannot register BONK asset for transaction Osmosis to Optimism, because Osmosis Network is not present in the Network list in https://portalbridge.com/advanced-tools/#/register
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9a833bc0-d64f-40f7-b705-4ea26792ea2b

**Comment by tsadovska** [comment]
Cosmos chains currently are not displayed on https://wormhole-connect.netlify.app/ and https://wormhole-connect-mainnet.netlify.app/.
Closing the ticket.
