### ISSUE TITLE
[Enhancement] Update text for bridging UX

### ISSUE THREAD

**Issue by tonyjin** [wormhole-foundation/wormhole-connect#1394]
## Describe the issue in detail
The below is too busy:
![Screenshot 2023-12-22 at 3 47 32 PM](https://github.com/wormhole-foundation/wormhole-connect/assets/689351/3dc5e2df-94c2-4ea8-8e36-c496e324f604)

## What is the expected/desired behavior
- Update text for "Manual Bridge" pillbox from `Approve a txn from your destination chain wallet` to `Approve transfer with destination wallet`
- Update disabled text for automatic route from `Not available` to `Transfer amount too low`
- Remove hover tooltip over disabled route
- Update text for manual transfer warning to `This transfer requires two transactions: one on the source chain and one on the destination chain. You will need gas on the destination chain.`

<img width="627" alt="Screenshot 2024-01-04 at 3 19 51 PM" src="https://github.com/wormhole-foundation/wormhole-connect/assets/689351/ac0beea3-bb27-4372-ba4e-119e344e2b48">

**Comment by aakashthumaty** [comment]
Some edits to the edits: 


1. Update text for "Manual Bridge" pillbox from 'Approve a txn from your destination chain wallet' to "Redeem by approving a transaction from your receiving wallet"

2. Update disabled text for automatic route from 'Not available' to "Total Transfer amount too low"

3. Remove Hover

4. Update text for manual transfer warning box to: "This transfer requires two transactions: one on the source chain and one on the destination chain. You will need gas on the destination chain."

5. Show the disabled automatic route on routes where we dont support it e.g. Eth -> AVAX, right now we only show this on routes where we support it but the amount is too low. Instead of the copy being "Amount too low" the copy should instead show "Automatic redeems coming soon". The goal here is to help users who've used the bridge in the past and simply clicked through to actively be aware of the different flow they are experiencing. 

6. Show both routes even when they are both available. Right now we hide the "manual route" and auto-select the automatic route, we should show both, while still auto selecting automatic. Again, the purpose is to help users who've used the bridge in the past and simply clicked through to manual to be aware of the different flow they are experiencing.

**Comment by aakashthumaty** [comment]
Cutting a new ticket for 5 and 6

**Comment by tonyjin** [comment]
Gaveled on:
1. Update text for "Manual Bridge" pillbox from 'Approve a txn from your destination chain wallet' to "Approve transfer with destination wallet"
2. Update disabled text for automatic route from 'Not available' to "Transfer amount too low"
3. Remove hover
4. Update text for manual transfer warning box to: "This transfer requires two transactions: one on the source chain and one on the destination chain. You will need gas on the destination chain."
