### ISSUE TITLE
[QA]Incorrect destination address in Wormholescan

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1423]
Preconditions:
Transaction hash for transaction Avalanche to Solana ( 0x72d46b2381840d9b1f845f4d89f7d2a75f36475d75e55fa8167c946b9ad89dcb )
 
Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.129

Tested from: https://deploy-preview-1401--wormhole-connect-mainnet.netlify.app/

Steps:
1. Click on Menu - resume transaction
2. Paste in the transaction hash ( 0x72d46b2381840d9b1f845f4d89f7d2a75f36475d75e55fa8167c946b9ad89dcb )
3. Select Avalanche Network
4. Click Search
5. Observe address for Solana wallet
6. Click on View on Wormhole scan
7. Observe Target chain Destination address

Actual result: Destination address is not matching Solflare wallet address

Expected result: Source chain and Target chain addresses represent wallet address

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6fdbff97-0d0b-431c-9eb1-f7b3f75bdcdb

![Screenshot 2024-01-05 at 09 07 42](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9b50a0d3-e48d-43ba-b361-374673beaece)

![Screenshot 2024-01-05 at 09 07 22](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4cbede6f-fe20-4897-b5a6-2c49565e8e04)

Correct address example for transaction Moonbase to Solana, [Wormholescan](https://wormholescan.io/#/tx/0xe5a2194284c0d862c04592329d27a46f113ba0c26d6713e2dc4f5482bfe17686)

<img width="1274" alt="Screenshot 2024-01-05 at 11 33 38" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/58de6427-a9c7-4deb-a83e-6a3738c45f6f">

**Comment by AigaD** [comment]
Reproduced from: https://wormhole-connect-mainnet.netlify.app/#
Attachment:

![Screenshot 2024-01-09 at 15 08 08](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/aa490910-e6d2-40c8-b912-fab0d3cfc6a7)

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/7246284e5d/#
Incorrect source chain address shown at [Wormholescan](https://wormholescan.io/#/tx/1/ec7372995d5cc8732397fb0ad35c0121e0eaa90d26f828a534cab54391b3a4f5/788887)
Attachment:

![Screenshot 2024-02-26 at 09 15 10](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/276653ec-d7f8-4fdf-9f69-9d4fea5a0cac)

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. Incorrect destination address on Wormholescan is shown for Injective target chain. Linked to https://github.com/wormhole-foundation/wormhole-connect/issues/1763.


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/0df2f051-2df6-44fe-a6c9-44546e91bccc

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/b1ba6e856a/
Incorrect Destination address shown in [Wormholescan](https://wormholescan.io/#/tx/0x9781a0f2f5f7e10c962193bdff1b01f219c602c122810a499a003d718db5e94b) for transaction to Injective (Leap)

Attachment:
<img width="1361" alt="Screenshot 2024-03-13 at 11 10 24" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e6bbf20a-0da7-4e79-a0f8-3dc44dc956cb">

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/b05f4e9322/
Incorrect destination address is shown in [Wormholescan](https://wormholescan.io/#/tx/0x2866c863dc175c4acb918d34524008f1f586dcfdbf501b3464415d6534139145). Destination address should be the same as Source address ins this transaction.

Attachment:
<img width="1202" alt="Screenshot 2024-03-19 at 11 02 53" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8d58ab2a-cefa-49d9-b34a-053e87dcd4b7">

**Comment by AigaD** [comment]
Tested from: https://portalbridge.com/
Incorrect destination address shown in [Wormholescan](https://wormholescan.io/#/tx/0x5204bd544659dbd9ba401d3de468e31d972fd28e5425abf67da405c92948a47f) 
Phantom wallet address - A4xMgXFWpSAA4aG3Beo4Nxe9fvEvcs43i4czrMki79F3
Address shown in Wormholescan as Destination address - 7SwLuUrdtfjt97snb1NS6QimL5iPndgvmCoLDYS6CDq3

Attachment:
<img width="1073" alt="Screenshot 2024-03-27 at 10 42 21" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1522a6d5-8e58-458a-9fbb-065632888901">

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/8228d00809/#
Incorrect destination address shown in [Wormholescan](https://wormholescan.io/#/tx/0xd5c4efc0001b3cc4e0ed957031c200e8f739463e45046c5c42d193f6cf70e9ee) 
Both Source address and Destination address should be the same in this test - 0xd493066498aCe409059fDA4c1bCD2E73D8cffE01
Attachment:

<img width="935" alt="Screenshot 2024-04-03 at 09 44 22" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/db9220fd-0834-47a9-9acf-c4cbbd26622c">

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Incorrect destination address shwon in [Wormholescan](https://wormholescan.io/#/tx/21/ccceeb29348f71bdd22ffef43a2a19c1f5b5e17c5cca5411529120182672ade5/119548) for transaction SUI from [Sui](https://suiscan.xyz/mainnet/tx/5rp14yJb749zQ9kbFv1vA5LUmLB1rnC9BvQxzXELkvm2) to Injective (Leap - inj19us9629lu3a684rp9tkd03fdyzs77ad7t9taxk )

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/dd2fd618-fb94-4d35-96bf-369e1e595b00

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
Transaction FTM from [Fantom](https://testnet.ftmscan.com/tx/0x489f27a2b68d1970f8287c1cd381b003277b94ed684083f372a9ba766ab854d4) (Rabby) to Alfajores (Rabby) has incorrect destination address in [Wormholescan](https://wormholescan.io/#/tx/0x489f27a2b68d1970f8287c1cd381b003277b94ed684083f372a9ba766ab854d4?network=TESTNET) destination address and source address should have matching wallet addresses.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2a0d4fa9-b78d-4f7b-b368-47b73157460f

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/ed4e22522f/
For transaction 0.001 W from Ethereum (Metamask) to Arbitrum (Metamask), destination address in [Wormholescan](https://wormholescan.io/#/tx/0x4b12f92c62d9fa2b2b7c3cf20c38e35f3816618f415389d3a491426c805c6850) is not matching, should be the same 0xd493066498aCe409059fDA4c1bCD2E73D8cffE01

Attachment:

<img width="1051" alt="Screenshot 2024-04-19 at 14 58 54" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e18bf225-3e61-468e-81db-ee6c9069c488">

**Comment by tsadovska** [comment]
Reproducible on [wormhole-connect](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDACIAjAJwEsATAc0gBFIAzAQwFcAbFdIxUCCEzIB7ALYA5HAHdhZANaIkraCjH5CEVZJQz5i9JArqBYVXJiKA6gDEAKgFljYAL4hnQA) [Testnet] when sending 0.001 WFTM from Fantom (MetaMask) to Sei (Leap).
* Send from tx: [FTMScan](https://testnet.ftmscan.com/tx/0xddbc80600839d316cb782a90f26516d81ec12282954de63fb8a766afa4ca5cf7)
* Leap account: sei1zusajl8703fxlztrpxyys43jgu06ep5wf9lffd
* Destination address on [Wormholescan](https://wormholescan.io/#/tx/0xddbc80600839d316cb782a90f26516d81ec12282954de63fb8a766afa4ca5cf7?network=TESTNET) sei1dkdwdvknx0qav5cp5kw68mkn3r99m3svkyjfvkztwh97dv2lm0ksj6xrak

**Comment by AigaD** [comment]
Reproduced from: [Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJNxEc00NIWIRcIybhnzFeABaQKkNik2CwOuTEXWwAXxDOgA#)
Incorrect destination address shown in [Wormholescan](https://wormholescan.io/#/tx/0x27d74be5e7eed076a0439607722af6a2681f210b15aa2cc8a434ae60952750f3), should match the Source address
Attachment:
<img width="950" alt="Screenshot 2024-04-30 at 09 29 31" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/739a4534-3bbe-4e2e-b580-b46a364e0921">

**Comment by tsadovska** [comment]
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ when sending 0.00001 USDT from [Celo](https://explorer.celo.org/mainnet/tx/0xd18f2611a4d13fdfa10f16162be0714ca8ba6034f6396ec274a791fc07954d0a) (MetaMask) to [Injective](https://explorer.injective.network/transaction/19D34A7488142A1C1AC5BE6D563888D778B173B48069D6384C5B07DBEC5250D6/) (Leap). Destination address on [Wormholescan](https://wormholescan.io/#/tx/0xd18f2611a4d13fdfa10f16162be0714ca8ba6034f6396ec274a791fc07954d0a) is aW5qMW1xcTB1NncweWV0eGdjdDRzazUzcG5jYXF6ejBlbWw4ajJhcDk3 instead of inj1mqq0u6w0yetxgct4sk53pncaqzz0eml8j2ap97.

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/bceadc8c64/ when sending 0.000001 tBTC from Avalanche (MetaMask) to Polygon (MetaMask). Destination address on [Wormholescan](https://wormholescan.io/#/tx/0x4e55f31603bc0eb179b2784c165271b11ae404c995b26e7c3283f0da78cd1329) is 0x09959798b95d00a3183d20fac298e4594e599eab instead of 0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012.

**Comment by AigaD** [comment]
Reproduced from: [Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJGTTdIhYhFwjJuGfMVoKZDLgpsU6wWC1yYiy2AC%2BIR0A%3D%3D%3D#)
Incorrect destination address shown in [Wormholescan](https://wormholescan.io/#/tx/0x80f40c9822dd734bd9258cadc86a8179acab33afca4649b5c5e83c49efab6671) for transaction 1.3 USDC from Base to Arbitrum, automatic CCTP route
Attachment:

<img width="975" alt="Screenshot 2024-05-15 at 13 18 38" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2a51bb18-64a6-4472-9ea9-7a5b707fd517">
<img width="1031" alt="Screenshot 2024-05-15 at 13 18 30" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9ed53adc-183b-4225-828e-fafe81f052c0">

**Comment by tsadovska** [comment]
Reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.0004 WETH (Avalanche) from Avalanche (MetaMask) to Polygon (MetaMask). Destination address on [Wormholescan](https://wormholescan.io/#/tx/0xa79ba0481c5d515e99897e3a8483e78b16f9d5135ef9954836d42ee0ab2feb21) is 0x227babe533fa9a1085f5261210e0b7137e44437b instead of 0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012.

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-2080--wormhole-connect-mainnet.netlify.app/
Incorrect Destination address for transaction 0.0004 ETH from Ethereum (Metamask) to Polygon (Metamask), Destination address for Metamask should be - 0xd493066498aCe409059fDA4c1bCD2E73D8cffE01
Attachment:
[Wormholescan](https://wormholescan.io/#/tx/0xe17b0f68e2d903f938926cd302f932e294620aa493293fab601a4f547db967fa)
<img width="1009" alt="Screenshot 2024-05-17 at 09 00 42" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f1fa325e-6d0d-440c-8fc2-3bc0dd647e44">

**Comment by AigaD** [comment]
Tested from: https://deploy-preview-2113--wormhole-connect-mainnet.netlify.app/#
Incorrect destination address shown in [Wormholescan](https://wormholescan.io/#/tx/0x655797cc11d5d9cf06d0b2cbf46ae9c21c2f9744986dcd7fca1311e7b94ab91c). Address shown should be zdv8TPs7wQR216Gghrk7GafmgM5oRnoNt66Zjo936tf

Attachment:
<img width="1013" alt="Screenshot 2024-05-23 at 08 43 38" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8b4263b8-717a-4485-b1c2-231111764b29">

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/3064c36d95/ [Mainnet] when sending 0.00101 WMATIC from [X Layer](https://www.okx.com/web3/explorer/xlayer/tx/0x04bd01a084efa6258f8ec8a63098b803da5f7a03c6c9472a7e78f149541cb473) (MetaMask) to [Injective](https://explorer.injective.network/transaction/A9E0E054AFB8BA80ECCAF3BC77D9B0E61DB1295F79760EFC6455AC603E84DFCC/) (MetaMask). Destination address on Wormholescan is `aW5qMW1xcTB1NncweWV0eGdjdDRzazUzcG5jYXF6ejBlbWw4ajJhcDk3` instead of `inj1mqq0u6w0yetxgct4sk53pncaqzz0eml8j2ap97`.

**Comment by tsadovska** [comment]
Reproducible on https://deploy-preview-2143--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.0004 ETH from [Ethereum](https://etherscan.io/tx/0xcb3bbb4409dc84d7e650a16826826f184aa0678dd0e32d751031336f5c956fed) (MetaMask) to [Polygon](https://polygonscan.com/tx/0xdb5218b9c53e0a9f35b316d432e1115ce7b781156284aa2c1aab00471ed2a81b) (MetaMask) with ETH Bridge route. Destination address on Wormholescan is `0x227babe533fa9a1085f5261210e0b7137e44437b` instead of `0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012`.

**Comment by agodlevska** [comment]
Reproducible on https://deploy-preview-2143--wormhole-connect-mainnet.netlify.app/# [Mainnet] when sending 0.0003 wstETH from [Arbitrum](https://www.google.com/url?q=https://arbiscan.io/tx/0xf646ba2a53db49161b0a4022c499caad638b60604612e8b7d61567cd94458734&sa=D&source=editors&ust=1717067943887860&usg=AOvVaw11KsCGV_VPdFFxz5Sr59Q3) (MetaMask) to [Base](https://basescan.org/tx/0x40276fc825a4a497fd50deab543104c94b8a03e9636d793444df121f8e06d7a6) (MetaMask) with wstETH bridge route. Destination address on Wormholescan is `0x610d4dfac3ec32e0be98d18ddb280dacd76a1889` instead of `0xd493066498ace409059fda4c1bcd2e73d8cffe01`

Attachment: 
<img width="1440" alt="Screenshot 2024-05-30 at 13 17 08" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/7cd945da-8a1f-4f79-b59c-89311ef5f934">

**Comment by tsadovska** [comment]
**1. Injective is a target chain** - Tested OK

Checked on https://wormhole-connect-mainnet.netlify.app/. Correct Leap wallet account is displayed on [Wormholescan](https://wormholescan.io/#/tx/0x08747c1ef574045d438a1fc33e751d5fcb89ab19b4a0ca6a6f30d0ab6574157e) when sending 0.001 CELO from [Fantom](https://ftmscan.com/tx/0x08747c1ef574045d438a1fc33e751d5fcb89ab19b4a0ca6a6f30d0ab6574157e) (MetaMask) to [Injective](https://explorer.injective.network/transaction/51F60B50B77B5130DF1916742A749230F0411DE193290D98D7DC3F48F19B47C0/) (Leap). 

Checked on https://portalbridge.com/. Correct Leap wallet account is displayed on [Wormholescan](https://wormholescan.io/#/tx/0xc0b2fb6be4b0fbffa22e5d8d5b64390e6d93b5f75ab3451eeda9facea67972df) when sending 0.1 WGLMR from [Moonbeam](https://moonscan.io/tx/0xc0b2fb6be4b0fbffa22e5d8d5b64390e6d93b5f75ab3451eeda9facea67972df) to [Injective](https://explorer.injective.network/transaction/D8C98A227020F3C5203F325A9FE94C83224A7812932D533ECECAC35CB754F692/) (Leap). 

**2. Automatic and Manual Bridge routes** - Tested OK

Checked on https://wormhole-connect-mainnet.netlify.app/.

Correct target address is displayed on [Wormholescan](https://wormholescan.io/#/tx/0xa34323d5ed2323564589333f3c378b3feb6d665348d226ac16e24f87d85b81bc) when sending 0.04 WAVAX from [Avalanche](https://avascan.info/blockchain/c/tx/0xa34323d5ed2323564589333f3c378b3feb6d665348d226ac16e24f87d85b81bc) (MetaMask) to [Fantom](https://ftmscan.com/tx/0xabe55408ac5f294cb1cb4f95efeaba38155d7c7fd98cbe75e7f219fb7ab273b8) (MetaMask) with Automatic route.

Correct target address is displayed on [Wormholescan](https://wormholescan.io/#/tx/0x8f972ca67ddf29c0c4b3c7261a2d3181372309f8b40f3ee209b1a1211683d082) when sending 2 FTM from [Fantom](https://ftmscan.com/tx/0x8f972ca67ddf29c0c4b3c7261a2d3181372309f8b40f3ee209b1a1211683d082) (Rabby) to [Celo](https://explorer.celo.org/mainnet/tx/0x60b55b18b224fdfba47ccc587f0409ea1878519ae3a6208be0fe401b96da8b9a) (Rabby) with Automatic route. 

**3. CCTP routes** - Tested OK

Checked on https://wormhole-connect-mainnet.netlify.app/.

Correct target address is displayed on [Wormholescan](https://wormholescan.io/#/tx/0x8627945d3bea79cec0959ca1110314a1a8456246629797a483838b799d5a56c3) when sending USDC from [Polygon](https://polygonscan.com/tx/0x8627945d3bea79cec0959ca1110314a1a8456246629797a483838b799d5a56c3) (MetaMask) to [Optimism](https://optimistic.etherscan.io/tx/0xd5d56133dda47ec486ce9fb034eb6416a8c08176f323e0607c6eda7a18773628) (MetaMask) with CCTP manual route. 

Icon that explains that this is not the final address is shown on [Wormholescan](https://wormholescan.io/#/tx/0xbe83c152ebcc66d6da1a8cf0c0289158bcb93b503aa3081519a9e6df2ea62217) when sending 1.3 USDC from [Base](https://basescan.org/tx/0xbe83c152ebcc66d6da1a8cf0c0289158bcb93b503aa3081519a9e6df2ea62217) (MetaMask) to [Arbitrum](https://arbiscan.io/tx/0x843bc4a890a4857dd60324f40d2bf07768831ee6552a4e21f692d2e87ad75341) (MetaMask) with CCTP Automatic route.

**Comment by SamantaCasal** [comment]
Regarding Eth Bridge cases: we must make a fix and add a field to the endpoint to solve this issue. The task is tracked in the ticket https://github.com/wormhole-foundation/wormhole-explorer/issues/1484. It is planned for the next sprint with a final date of 02/07.

**Comment by tsadovska** [comment]
Incorrect target chain address is shown on Wormholescan when sending Yaku token from Avalanche (MetaMask) to Solana (Phantom) with Native Token Transfer Manual route. Address `nTtPcmsVY4f86cSREmnio5tUyiK58HBqBeDwaUYQt6t` is shown instead of `4bG8RegzdEW5EPoYUthdopyQdYeNerhiLUdbvx1HEGdU`. 
* Send from tx: [Avascan](https://avascan.info/blockchain/c/tx/0x8562742644a0aeac481f83edf24d76fea3729940ad3f1c83e90b7a999bb8807c)
* Send to tx: [Solana Explorer](https://explorer.solana.com/tx/Ry6UbM6CRSrVr5z32jmwxwVyn7mh6XxXpuVX4MCtRJhFc3LbVPgbQM9ogzodrHcuxzDMYnziw77StLTurtrDBaT)
* Link to [Wormholescan](https://wormholescan.io/#/tx/0x8562742644a0aeac481f83edf24d76fea3729940ad3f1c83e90b7a999bb8807c)

**Comment by tsadovska** [comment]
Incorrect target chain address is shown on Wormholescan when sending WGLMR from Moonbeam (MetaMask) to Solana (Phantom) with Manual route. [4R6nLCZvUVvueDhXdKmYynvmoYwyCJ6HXavjXJXmDQGW](https://solscan.io/account/4R6nLCZvUVvueDhXdKmYynvmoYwyCJ6HXavjXJXmDQGW?cluster=) address is shown instead of [4bG8RegzdEW5EPoYUthdopyQdYeNerhiLUdbvx1HEGdU](https://solscan.io/account/4bG8RegzdEW5EPoYUthdopyQdYeNerhiLUdbvx1HEGdU).

Reproducible from:
* https://preview.portalbridge.com/b1f3c5115d/ (Connect v2)
* [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYBEBbAhgS2tSAXJANCOGAE4D2ArrpAM6IDaJEAdGwCICiAYgIICqAGQAqAfQBKAeX7DOAZQJgAsmgCeaaOKo0iEVm2i5cW6nQAUoPXtzkA1jHphLVvYIwATcqIDutXJ2EACUZmFwhnMKsAYwALTGhEJE5cGMhSSEoUQlDIsHRoNABzNMSABgAPACMATgAWAA40aoBmeoAmAHZ3ADZG9u5ugFYARmbed2GO%2Buru2vY0Bo6AM0g2gCF2auzcqxt7BOQK5ebqgGFB%2BuHuQerBtcHmqMGoyuHqyvZSyual%2BvdebpRFqDThtU5oUrbHYQXCkDS0KKQDCwEpgJjQqwRDEQNDudzpWiOJAVXjDXinU7DSDdSDuNBrNqXbiQSruarDTjNEaDUotbjDLhMtrPSG6bHWVQAB0giW85FIKBi5AANpAodiAL5i6EAXW1kS1ORcWNysXiiTWCPVO3yRVRxPK3WqTMG3Tawydw1OayWnPY7nYgzatXcnA6w1KHW6lQ61W4pV4pU69WtuT2MDK5TagMGkFKwyDIbanDd9QTDW4bSepSWA3YkA6kCDnBmwy9qcisPhiORqPR4pNGNx%2BLoRIqlUgzW4jdKvQ6xdK7gGp3YHW43C5aw6aAWa1etVq3XYp2qzu6HehuClMuQcoVStVF4N%2BtyeqNVkNr5fegA6iFoYOYRmlgiRyCqGhoE%2BVi2sUpCJAAcsIuC8Gg5DsAAUjE9iBJAaAAGr8IE0CqDE3iVAACvBvDwd0P6FGskqBLYgRrMIUTdO4HSwIIADSUHWHYGbIPUgx4Ws3AAIoAFonsIUm2EsaCSrgaw%2FgAVrA%2FDeB0ACalRSWpqhBgCKBqbg5EAOJqX4Em8CgEn8TCcLQAiSIonBaLvpEgE7MOBJEohyGoRhWGQDh%2BGEcRpEUVRNF0QxTEsWxHFcbxjkuFe0qyvKioqmq365J%2BGJvtiACOlDkDQHlIPBpU9AAGqVvD1IIlS0KclAWfUSiCD%2BP6UOR9RDPBeHdGp4jDEolT1ZAPHlOwtSBLxGH8UVuQ%2BdEcQgcgySpOkmTpTB9oVFEkbrGSnBLM0zQ0v6TbVImtQzKel21JA9TcE0gZ1LwDTpemBwOmsNafWWpSlPUQ1NmuQ14kGsw1BcbSVG04z1B0KM1MM%2F3Oa5vYef22IbZEfmjpm7CVIMgxPW0nFvKU7DDJUaCcPU5KVJwpQnG2py1JyYa1Nm6OlFE6W7Ne2X3nlYtgGtOwlTscthMTEDAYDvCkJUGCwgdBUuEd1UVA813uAmUQArUCw8uMPTMtOR5HqMHSDNO2beg0tT%2FYJgMVMDtZoGDENQ4MMMce48O1Ij7Qo2jGPI%2ByOPdm5fZecrqck3i%2Fnk8MAe8GsTp5km3Q0vUW7smgBZrLzzvDLUBZjDytSDGg5562mEu3jlD75enH5t3oCuFf3KtgGriSSMpGAoBgtBZP3EAG5mOe1PyaCxjWbRTksNQdPOMyAvnG4cacPQXFzzSQKMXv7Jmfug%2BDQc0iH3Cw%2BH2aR7c0eo%2B46OYwn89gC7C5Hs7l%2FwDl7i4UmhJMzvHYPUGMlNOinF%2BtSDorQogbHpEuEYpw2jBmLs7bokZmjuBljCDuSA7y5UfAAiAStIiD2fOnEeY9kBrDQLQHu2JF6HHKMbEhZsLZWwTHibodsozsEds0Z2rtuju3qJ7ABANb4gwDg%2FSGT9Q5w3flHZG39f7x2xko3GICU7iicBAqwUCxzzRzmzfO1RC7ZhLmXHOldq4jDrg8Xgjdm6t0sRKLKncpY0ICfQsIjCwjhLAJE2W%2BoNQAEoxRvhIJQTh4haR0AwIUA4OtIBEBIADdq5BoBLGyYgLEvh%2FBBDalECpRp7CqFlH4AIgRakdloKoFAlQVTNOqYEDsBRcC9lOFtQGlpRbfgBgASXcPU00YyLRWj1tYzM2Ynh5gLMGdwxZSzlg%2BlWHktYjwNibMWVs7Zvz0IwFEEpiQYhGElPQAA9M8jhnDcC0BYLcrAxQoi2HIN88gKBnk%2FJcs8qedpaDPOGJDZotRnl%2BA0HSUg7hnlVNaSwSU0BCgdjBRZSA%2FzyCzNlHCSU0p3AAFo%2FB4BiHilU8pEgAGIxi8CnNwDs7hCWQuVI4WF8T9Q%2FloOBAo8yXCNMSEKkVkFvydO6b05AP5BloGGSiUZ5pkBgWVBBDsMy5kWIWRqpAWqdUrMzmTYSolxLSVkvJRSylVIaS0rpfShljLdFMuZKyNk7IOSud%2BG5dzkAPNwE8%2BArz3l4C%2BWCv5AKgUgrBdCyFxRoVcghh0RFuBkVoFRei4FpBu6iGVOQQoXgliUGVMqUQtzi2kFEKQQolRRBtAfpKcooh5zkowKIbeUZuhoCiCJNAWKcUAH5JgQ16NMam9KsAEqJSS4J1CuEuC5VEHljhugCtCD%2BWlaQMgoDFVYCViq937TnkaOVPTlSSuVaqyA6rtpJBSPu3WRo9VHpcKw59e0D1PlWbwu%2BajwYaOhi%2FMOEddExx%2FnHLGHZrm3MBiGsNEbCRRqBb8wlcbbkJvIFgJN6AU3PLTejTN2bc1yhQAWvKRaS1lorVWmt8p62Nuba29tnbJTdt7cXAdQ6R2FHHR0SdkNbiKKNPirDxL9WUK7tLb8a6N2IH5aEOWP4c1ax1oeg14rIBNMVRp7WpA31hCvQqpASrvxDJGYs5AGtNPGYvWED9OmgK2aQPZozJmM4jmgYB1RgdQPP1fpBz%2BejY5%2FyMUaBDQakDIZeW8tDnyMM4qk%2FG0FeHwXJroMRnkpGkXQBRWiyj1HVS0dLT2hj1aGV1obU2lt4M20draF2ntMZeODubgJoTInp3iaApl%2BdALF2yZCSuqwin0C8uU%2FUbdVgfzkEntPWen6IAnos4t4Zy2nMuDMzexVd6bNGonltmeO3dje0XT5b9J2p5nf%2FeavzQMAvqODlot%2BCMwvQYMXB%2F1RpA1IceQlyNyWY1pZwxl%2FDELCM5ZIxmgrRW81UcLcWir5bK3VdrSx%2Br7HmutZ4%2F2zrw7sWCYnUNUTM7vySYXTJqh3dOXcqm3y2bqnBXM04atsA62fzs%2FG3oPbt6rMqqO0%2B9hnDdWXf1dd9zYu%2BdWMezYoDgW3vge0Z9pG33YP%2F2iwGxD9ygfhsSx86NmXY2Aoh4m6HULcvprI4VnNxX80o7o5VjHTHausYa6UJrnHuPtcJ%2FxknPXyd9dndAIb0nJbLoZ%2BupnM25txJABqAA3EAA%3D%3D%3D) (Connect v2)
* https://portalbridge.com/ 

Transaction details:
* Send from tx: [Moonscan](https://moonscan.io/tx/0xe1574e962fcf7d37f116e134c0e09d81f658ef4cbc13f2744df6bddf99ce8a4b)
* Send to tx: [Solscan](https://solscan.io/tx/57YKEdfGmYZrdjSnJjSnHi6VpyJHGSsRK3vsp7pmyErgMfGmF7Gs85raBPyR9NWMqnfDG8TLZwKzni6P1TQUj9fp)
* Link to [Wormholescan](https://wormholescan.io/#/tx/0xe1574e962fcf7d37f116e134c0e09d81f658ef4cbc13f2744df6bddf99ce8a4b)


![Screenshot 2024-09-13 at 10 54 28](https://github.com/user-attachments/assets/1befc35e-29f4-48ff-be5c-a286de610c28)


![Screenshot 2024-09-13 at 10 55 40](https://github.com/user-attachments/assets/07bd8cdd-4f2c-4c4c-8134-2240d0f8fbdb)

**Comment by agodlevska** [comment]
Reposted to Wormholescan repo - https://github.com/XLabs/wormscan-ui/issues/871
