### ISSUE TITLE
[QA] [Mainnet] Notification that account needs more SOL is shown although enough SOL is available

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1693]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome.

Precondition: User has SOL on Solana (Phantom), in my case 0.006014 (~$0.62). 

Steps:
1. Prepare to send 0.0001 SOL from Solana (Exodus) to Avalanche (MetaMask)
2. Click "Approve and proceed with transaction" button

Actual result: Notification that account needs more SOL is shown.

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d10d41fe-2f1c-494b-94a3-54c4ab7195fe)

## What is the expected/desired behavior
User can approve transaction in Exodus wallet.

**Comment by tsadovska** [comment]
Issue is reproducible on https://portalbridge.com/ [Mainnet] with the same scenario, when sending 0.0001 SOL from Solana (Exodus) to Avalanche (MetaMask). User cannot approve transaction in Exodus wallet.

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/ [Mainnet] with the same scenario, when sending 0.001 SOL from Solana (Exodus) o Avalanche (MetaMask). User cannot approve transaction in Exodus wallet. 

![Screenshot 2024-03-10 at 18 39 22](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a9e9c1e1-27ee-492f-bc62-fc91c2319e60)

**Comment by tsadovska** [comment]
Issue is also reproducible on https://portalbridge.com/ [Mainnet] when sending asset from Solana. User has 0.698045 SOL ($0.70) in Phantom wallet. "Source chain gas estimate" is ~ 0.000015 SOL (~$0.00). "Not enough SOL" warning appears after clicking on "Approve and proceed with transaction" button. 


![Screenshot 2024-03-18 at 19 22 46](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/282e8696-8caf-41ec-8c51-cfd5559f9ed2)

**Comment by tsadovska** [comment]
Issue is also reproducible on https://preview.portalbridge.com/b05f4e9322/ [Mainnet]. Warning "Not enough SOL" is shown when user has more SOL that is needed to pay for fee. 

![Screenshot 2024-03-19 at 10 06 12](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/68186216-bfa6-442a-95c7-32a16b09e699)

**Comment by Slinger2020** [comment]
My sol refusing to send out,on phantom is not showing as wrapped sol but on sol scan the address is that of wrapped solana 
![Uploading IMG_4605.png…]()

**Comment by agodlevska** [comment]
Checked on https://portalbridge.com/. 
The bug is no longer reproducible, the transaction now completes successfully. 

Sending 0.00001 USDC from [Solana](https://explorer.solana.com/tx/4A1A3S58BjuzYP5Q4aDfubPZQdN9XeXYQg9aeZTfiyRgWDpop6a6yp1Vz6R31Kt9poHEG6dJ5YhRoNePFrAve9kr) (Phantom) to [Fantom](https://ftmscan.com/tx/0xec1d469f887be3d0a9869090c7daf2ce432e92facaab6fea3fe3f43f5b700094) (MetaMask).

- Gas fee estimate: ~ 0.000015 SOL(~$0.00)
- Gas fee: 0.002477 SOL (~$0.36)

Checked on https://wormhole-connect-mainnet.netlify.app/.
The bug is no longer reproducible, the transaction now completes successfully. 

Sending 0.00001 USDC from [Solana](https://explorer.solana.com/tx/4LMECbbUweqox15ysWgTQZQcAGaPrt4NHkw3KfNTxhmiEVjh1FK8DUQSPaGf5tGEecYaoZ8UbkXwLffSERUErDed) (Solflare) to [Fantom](https://ftmscan.com/tx/0x677685ba63ab0eeed7fb8d9c96111989ea2e5e66203bf7a120bc3a983961639a) (MetaMask).

- Gas fee estimate: ~ 0.000015 SOL(~$0.00)
- Gas fee: 0.002477 SOL (~$0.37)

Closing ticket.
