### ISSUE TITLE
[QA] Cannot add USDC.e token to Rabby wallet

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1884]
Precondition: Rabby wallet connected

Environment:
OS: macOS Ventura 13.0.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://preview.portalbridge.com/8228d00809/#

Steps:
1. Prepare to send 0.01 USDC from Ethereum to Fantom
2. Select Automatic Route
3. Click Approve and proceed with transaction
4. When transaction is completed click on Add USDC.e to your wallet
5. Observe

Actual result: Message `Token not found from this contract address` shown on Rabby pop-up window, cannot add USDC.e to Rabby wallet

Expected result: USDC.e token added to Rabby wallet

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ffaad120-2fad-4c22-8586-346d795db73f

**Comment by einaralex** [comment]
Just chiming in because I was researching this in my own project.

[In the implementation](https://github.com/wormhole-foundation/wormhole-connect/blob/cc8fabcacdda921bec387c9235506c5aa24a68b9/wormhole-connect/src/views/Redeem/AddToWallet.tsx#L74-L84), chainId is being sent.
I don't think Rabby can read `chainId`, I'm pretty certain it only accepts a `chain` string.

I'm not exactly sure what strings they accept, but I think it's most production case-insensitive chains name as specified in https://chainid.network/chains.json. 
The following have worked for me: "ethereum", "polygon", "gnosis".  

I could not do this with a token on Amoy, which is probably because it was added as a custom network to Rabby.

It should be a very easy 'first issue', to add Rabby support for production chains :)

**Comment by agodlevska** [comment]
Checked on https://portalbridge.com/.
Sending 0.01 USDC from Ethereum (MetaMask) to Fantom (MetaMask). 
The USDC.e token successfully added to Rabby wallet. 

Closing the ticket.
