### ISSUE TITLE
[QA][Mainnet] BSC explorer link leads to invalid transaction hash result

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1905]
Precondition:
Metamask wallet connected

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://portalbridge.com/#

Steps:
1. Prepare to send 0.001 WETH from Polygon to BSC
2. Click Approve and proceed with transaction
3. When transaction is completed click on explorer links

Actual result: BSC explorer link opens result `Oops! An invalid Txn hash has been entered:`

Expected result: Information about transaction is shown at BSC explorer

Attachment:
[Polygon explorer](https://polygonscan.com/tx/0xf80c7a36fc325ab078e0f0d4f0cc1f9db984be9286a5846c3cfe8509f790cb04)
[BSC explorer](https://bscscan.com/tx/a5aaa446f41e8f95c079004575bc7646d003423e7a019a0ed90f1f6ca49fdd1f)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/725103d8-7587-47c3-93b4-5e294cd522a5

**Comment by AigaD** [comment]
Tested from: https://portalbridge.com/
Issue no longer reproduced. Closing the ticket.
BSC [explorer](https://bscscan.com/tx/0xf165a80788da9b3b479f50ec5797f04aa35fe2ae3856bda8e86ca515edce551b) link leads to correct transaction details.

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/78ca7fff-eff4-4e44-95a9-4e1b3e9dd7d2

**Comment by agodlevska** [comment]
Reopening the issue. 
Issue reproducible on https://preview.portalbridge.com/321a610744/ when sending 0.05 USDT from Polygon to BSC. 

- Send from tx: [Polygon](https://polygonscan.com/tx/0x99cfcd5089e28d60b821bda7edfd88e6e8e6cbfe86afe568c35a78defa6fcdf1)
- Send to tx: [Invalid link](https://bscscan.com/tx/9083f1b1aed923d216b69cb8472170b60928425627b58d94886d2eca5c25a61e) instead of [correct link](https://bscscan.com/tx/0x9083f1b1aed923d216b69cb8472170b60928425627b58d94886d2eca5c25a61e)
- Link to [Wormholescan](https://wormholescan.io/#/tx/0x99cfcd5089e28d60b821bda7edfd88e6e8e6cbfe86afe568c35a78defa6fcdf1)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://portalbridge.com/.
Scenario checked: 0.0001 USDT transfer from Polygon (MetaMask) to BSC (MetaMask)

* Send from tx: [Polygonscan](https://polygonscan.com/tx/0x558a41dc383a4333a7d60655818b85774d39d5497d48c142a594becbb4802c51)
* Send to tx: [BscScan](https://bscscan.com/tx/0x37d3e4046d44787600f9f556548bf96363531ad011830c9848ad7130ffb5a079)

Closing the ticket.
