### ISSUE TITLE
[QA] Native token amount in "Native gas" section should have more decimals after comma - ETH (Arbitrum) 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1906]
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome. 

Steps:
1. Prepare to send 4 USDC from Optimism (MetaMask) to Arbitrum (MetaMask)
2. Enable "Native gas" section
3. Change slider position
4. Check if 0 ETH (Arbitrum) amount has changed

Actual result: Amount has not been changed. 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/6968df57-b396-4fcd-aebc-430a14fd16bb

## What is the expected/desired behavior
Amount has been changed.

**Comment by AigaD** [comment]
Precondition:
Rabby wallet connected
Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85
Tested from:
https://deploy-preview-1869--wormhole-connect-mainnet.netlify.app/
Steps:
1. Prepare to send 5 USDC from Base to Arbitrum
2. Select Automatic Route
3. Change the slider in Native gas section
4. Observe

Actual result: Value for ETH (Arbitrum) native gas token stays on 0 ETH (Arbitrum), also in Preview section "Native gas on destination" is not showing because the amount stays on 0 ETH

Expected result: Value shows Native gas token amount
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/80be0a08-39d8-45f7-8412-873257ac4aec
<img width="1037" alt="Screenshot 2024-04-12 at 12 42 57" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/571d0696-df94-4524-9b4d-070e5771abab">

**Comment by AigaD** [comment]
Tested from: [Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJGTTdIhYhFwjJuGfMVoKZDLgpsU6wWC1yYigKoBlBgGFlqy2AC%2BIL0A#)

```
{
  env: 'mainnet',
  "bridgeDefaults": {
    fromNetwork: 'base',
    toNetwork: 'arbitrum',
    token: 'USDCbase',
  }
}
```

Native gas value for ETH (Arbitrum) is not shown when moving the slider position 
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a840586d-aa53-46dc-832e-64bb6bc7ab3a
