### ISSUE TITLE
[QA] Indication that Metamask wallet is connected while actually connection to Rabby wallet is made

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#2094]
Precondition:
Rabby wallet enabled
OKX wallet enabled

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
[Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJFgBWkAMa4MsSIWIRcIybhnzFI7inMZuuwWANyYi22AC%2BIV0A%3D%3D#)
{
  env: 'mainnet',
  "bridgeDefaults": {
    fromNetwork: 'arbitrum',
    toNetwork: 'optimism',
    token: '',
  }
}

Steps:
1. Click on Connect wallet
2. Connect wallet offered Metamask/Rabby
3. When wallet is connected on OKX pop-up click Disconnect wallet
4. Click Disconnect wallet also by pressing on wallet -> Disconnect
5. Refresh the page
6. Click on Connect wallet
7. Select Metamask
8. On OKX pop-up select Rabby
9. Observe wallet connected

Actual result: When OKX wallet and Rabby wallet is enabled occasionally either Rabby or Metamask wallet is shown in available wallet list, but by disconnecting both in OKX pop-up "Disconnect wallet" and by clicking Disconnect, when user connects Rabby wallet, Metamask icon is shown

Expected result: When Rabby wallet is in use, Metamask wallet is not connected

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b8738825-ed08-4b81-b9b8-9bdb7e51e3a3

**Comment by agodlevska** [comment]
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) (connect v2). 

The issue is still reproducible, but now the Rabby wallet option is completely unavailable when the OKX wallet extension is enabled.

Attachment:

https://github.com/user-attachments/assets/8f61eaa6-4bea-4d23-bc68-d0da1c7a9610
