### ISSUE TITLE
[QA] [Mainnet] Avascan link leads to invalid transaction hash result

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#2150]
## Describe the current behavior in detail
Checked on https://deploy-preview-2143--wormhole-connect-mainnet.netlify.app/# [Mainnet] with macOS Sonoma 14.5 and Google Chrome Version 125.0.6422.113 (Official Build) (x86_64).

Steps:

1. Prepare to send 0.0004 ETH from Ethereum (MetaMask) to Avalanche (MetaMask)
2. Click "Approve and proceed with transaction" button
3. Click on "Avascan" link in "Send to" section

Actual result: Page is opened https://avascan.info/blockchain/c/tx/aaa8b7490893ea5e2bdb9fbceea1d0881fda5d9917e5ffe2c7bb8add2c5d4bdc 
Error: "Hash not valid"

Expected result: Correct link is opened (Snowtrace not Avascan)
https://snowtrace.io/tx/0xaaa8b7490893ea5e2bdb9fbceea1d0881fda5d9917e5ffe2c7bb8add2c5d4bdc?chainId=43114
## Notes / Attachments
Similar issues: https://github.com/wormhole-foundation/wormhole-connect/issues/1919, https://github.com/wormhole-foundation/wormhole-connect/issues/1909, https://github.com/wormhole-foundation/wormhole-connect/issues/2057, https://github.com/wormhole-foundation/wormhole-connect/issues/2086.

<img width="1440" alt="Screenshot 2024-05-30 at 12 09 28" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/96ef7017-b04e-4f67-8ff8-773ef1b7157a">

**Comment by agodlevska** [comment]
Reproducible on https://wormhole-connect-mainnet.netlify.app/. 

Sending 0.002 BNB from BSC (MetaMask) to Avalanche (MetaMask) with Automatic Bridge. 
Explorer link opened [invalid link](https://avascan.info/blockchain/c/tx/8d3ac257b78663319a6d36b4b545f29a6f638ad596835dd38975c19243c21fd5 ) instead of [correct link](https://avascan.info/blockchain/c/tx/0x8d3ac257b78663319a6d36b4b545f29a6f638ad596835dd38975c19243c21fd5).

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/3365c86aff/ [Mainnet] when sending 1 USDT from Arbitrum (MetaMask) to Avalanche (MetaMask) with USDT Bridge. 
* Send from tx: [Arbitrum Explorer](https://arbiscan.io/tx/0x4dff6c9cf2e625658a0d1c46516ded05443192c6519782750b174f79faf1e9bd)
* Send to tx: [incorrect link](https://avascan.info/blockchain/c/tx/c0c0c6059fe3a7adae3a670bd6052bf45790e6c45442d2a0de8703ddd394d7e5) link is opened instead of [correct link](https://avascan.info/blockchain/c/tx/0xc0c0c6059fe3a7adae3a670bd6052bf45790e6c45442d2a0de8703ddd394d7e5) to Avascan
* Link to [Wormholescan](https://wormholescan.io/#/tx/0x4dff6c9cf2e625658a0d1c46516ded05443192c6519782750b174f79faf1e9bd)

**Comment by tsadovska** [comment]
Reproducible on https://portalbridge.com/ when sending 0.001 ETH from Ethereum (MetaMask) to Avalanche (MetaMask) with ETH Bridge. 
* Send from tx: [Etherscan](https://etherscan.io/tx/0xbe4989ed9c5e1f796001d8b2d822cc0489bda0fc4c42a7f1f8e37f3215da5fef)
* Send to tx: [Avascan](https://avascan.info/blockchain/c/tx/e9abb828e52d9bdc08108080836fc2c88fe6d8913c8f33332b91998228fd24bb)
* Link to [Wormholescan](https://wormholescan.io/#/tx/0xbe4989ed9c5e1f796001d8b2d822cc0489bda0fc4c42a7f1f8e37f3215da5fef)

**Comment by agodlevska** [comment]
The issue is no longer relevant after the redesign, link on destination chain is no longer displayed.
Closing the ticket.
