### ISSUE TITLE
[QA] Asset name is "MATICpo" instead of "WMATIC" on Wormholescan

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2160]
## Describe the current behavior in detail
Checked on https://deploy-preview-2153--wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS Sonoma 14.4.1 and Google Chrome Version 125.0.6422.142 (Official Build) (arm64).

Steps:
1. Prepare to send 0.0001 WMATIC from Injective (Leap) to Solana (Phantom)
2. Click on "Approve and proceed with transaction" button
3. Click on "Claim" button
4. Click on [View on Wormholescan](https://wormholescan.io/#/tx/3104/aeb534c45c3049d380b9d9b966f9895f53abd4301bfaff407fa09dea8ae7a924/35291) link
5. Observe asset name in "Target chain"

Actual result: Asset name is "MATICpo".
Expected result: Asset name is "WMATIC".

## Notes/ Attachments
* Send from tx: [Injective explorer](https://explorer.injective.network/transaction/ED24ADDF5EF0B075DFA3E5E41D87109670B985319704D038D95A280665DF4A71/)
* Send to tx: [Solana explorer](https://explorer.solana.com/tx/2zpKbTRSWgPB6GfXAji26JQc4n8QcXqcD7fpNEgBDbZ6taTasLEkfshMbVsezowgeQqFbxWuTy4niEEfGhJ9bcmo)
* Link to Wormholescan: [Wormholescan](https://wormholescan.io/#/tx/3104/aeb534c45c3049d380b9d9b966f9895f53abd4301bfaff407fa09dea8ae7a924/35291)
* Link to MATICpo: [Solscan](https://solscan.io/token/Gz7VkD4MacbEB6yC5XD3HcumEiYx2EtDYYrfikGsvopG?cluster=)

![Screenshot 2024-06-03 at 17 20 25](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/6221bea1-d81a-4736-a995-16eb2a0f653a)

**Comment by agodlevska** [comment]
Reproducible on https://preview.portalbridge.com/3b81f32422/
Sending 0.05 WMATIC from Polygon (MetaMask) to Solana (Phantom)
Asset name is "MATICpo" instead of "WMATIC" is shown in "Target chain".

Attachment: 

<img width="1440" alt="Screenshot 2024-06-06 at 12 39 21" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/b5701f0c-796e-40df-9beb-37fdf908acf8">

**Comment by agodlevska** [comment]
Reproducible on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D). 
Sending 0.001 WMATIC from Base (MetaMask) to BSC (MetaMask). 
Asset name is "MATICpo" instead of "WMATIC" is shown in "Target chain".

- Send from tx: [Base](https://basescan.org/tx/0xfc9cd92893f6254a9eeb89cf3aecb75bf0e30427508384aa631235e145521b4f)
- Send to tx: [BSC](https://bscscan.com/tx/0x94253fb05da2d1286c1b9a0217417e6084ce362a6238b7baf6dfa50ea0224d04)
- Link to [Wormholescan](https://wormholescan.io/#/tx/0xfc9cd92893f6254a9eeb89cf3aecb75bf0e30427508384aa631235e145521b4f)

Attachment:
<img width="1440" alt="Screenshot 2024-09-11 at 10 32 46" src="https://github.com/user-attachments/assets/2391f7a1-bb28-499e-9c73-4b05b3aa6fa3">
