### ISSUE TITLE
[QA] An error page opens after clicking on "Install Spika" option

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2299]
## Describe the current behavior in detail
Checked on https://portalbridge.com/ [Mainnet] with macOS Sonoma 14.5 and Google Chrome Version 126.0.6478.183 (Official Build) (arm64).

Preconditions:
Spika extension is not installed or is disabled.

Steps:
1. Select Aptos network
2. Click on "Connect wallet" button
3. Click on "Install Spika" option.

Actual result: An error page opens https://chrome.google.com/webstore/detail/spika/fadkojdgchhfkdkklllhcphknohbmjmb. 

## Notes/ Attachments

![image](https://github.com/user-attachments/assets/90655cfc-bb6d-48f6-93a0-0f448eeddc04)

**Comment by agodlevska** [comment]
Checked on https://portalbridge.com/ and https://wormhole-connect-mainnet.netlify.app/. 
Upon attempting to download the Spika wallet, a page appears stating, "This item is not available." The extension has been removed from Google Chrome, so this message is the expected behavior.

Closing the ticket. 

Attachment: 

https://github.com/user-attachments/assets/acc137b8-34f0-419c-87cf-8585a88f90f8
