### ISSUE TITLE
[QA] An unexpected error occurs after clicking on "Review transaction" button

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2369]
## Describe the current behavior in detail
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) with macOS Sonoma 14.5 and Google Chrome Version 127.0.6533.100 (Official Build) (arm64).

Steps:
1. Prepare to send 0.001 FTM from Fantom (MetaMask) to Celo (MetaMask)
2. Do not change the route option, Automatic Bridge route is selected by default
3. Click on "Review transaction" button|

Actual result: An unexpected error occurs. 
Expected result: Transaction proceeds without errors.

## Notes/ Attachments

```
Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Uh (main-XtpqVqCV.js:39:19312)
    at Object.ji [as useRef] (main-XtpqVqCV.js:39:22371)
    at react_production_min.useRef (main-XtpqVqCV.js:10:7360)
    at useGuaranteedMemo (main-XtpqVqCV.js:269:178373)
    at et (main-XtpqVqCV.js:269:179420)
    at main-XtpqVqCV.js:269:181976
    at Object.WormholeIcon [as icon] (main-XtpqVqCV.js:276:219928)
    at SingleRoute (main-XtpqVqCV.js:309:57866)
    at Nh (main-XtpqVqCV.js:39:18669)
    at cj (main-XtpqVqCV.js:41:3408)
```

https://github.com/user-attachments/assets/fe1f0e7a-a024-4b4c-ba91-a485eb79f91d

**Comment by agodlevska** [comment]
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D). 
The issue is likely due to the insufficient amount for an automatic route. Currently, it's not possible to verify this due to issue #2501. The ticket will be reassessed once #2501 is resolved.

Attachment:
<img width="1437" alt="Screenshot 2024-09-04 at 17 24 33" src="https://github.com/user-attachments/assets/f12e15fa-6e15-4b23-8eb4-1236c59a4d63">
