### ISSUE TITLE
[QA] Token list in "To" section is incomplete

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2659]
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/b1f3c5115d/.

Steps:
1. Select Moonbeam network in "From" section (MetaMask wallet was auto-connected)
2. Check available tokens 
3. Refresh the page
4. Select Moonbeam network in "To" section (MetaMask wallet was auto-connected)
5. Check available tokens

Actual result: The same token list is displayed. 
Expected result: Some tokens are missing. 

## Notes/ Attachments
Issue is also reproducible with other assets, for example Base and BSC. 

![image](https://github.com/user-attachments/assets/cdfd9fed-3d4f-4b82-9855-65d63efb45a3)

![image](https://github.com/user-attachments/assets/fa18c2e5-a763-4f6a-a147-86aba6d8b652)

![image](https://github.com/user-attachments/assets/f2f3e8ee-d230-4c4a-b536-469181c7619c)

**Comment by Wesleyleung** [comment]
I'm guessing this is happening because only GLMR and WGLMR are default tokens for Moonbeam. The other wormhole-wrapped tokens show up in "From" because you have a balance of those tokens. They do not show up in "To" unless the user also selects the corresponding wrapped token in "From". This logic makes it so that users can only bridge Wormhole-wrapped or non-default tokens that have a balance of.

**Comment by tsadovska** [comment]
Closing as expected behaviour. 
USDT balance is displayed on Moonbeam in "To" section when corresponding token is selected in "From" section. 

![image](https://github.com/user-attachments/assets/c0a4fc7c-99a7-48a0-843e-2217ceef96b1)
