### ISSUE TITLE
[QA] Status "Wrapping up" is shown for transaction that is ready to claim

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2786]
## Describe the current behavior in detail
Checked  on https://deploy-preview-2778--wormhole-connect-mainnet.netlify.app/. 

Steps:
1. Send 0.02 WAVAX from Base (OKX wallet) to Scroll (OKX wallet)
2. Wait until transaction is ready to claim 
3. Check transaction status in the In-progress widget 

Actual result: Status "Wrapping up" is shown for transaction that is ready to claim
Expected result: Correct status is shown. User should be informed that he/ she can claim assets.  

## Notes/ Attachments

https://github.com/user-attachments/assets/148473b9-676b-4958-9854-e74658879470

Loading icon instead of "Wrapping up" is displayed after page is reloaded.  

![image](https://github.com/user-attachments/assets/9bc7e2c0-fd9b-4561-92c0-b5c3fa055fed)

**Comment by emreboga** [comment]
This is a known issue. We track the transaction status from WHScan API and it doesn't have an indicator of a manual transaction's "Ready to claim" status. It's not different than the transaction is being in-progress, there for it still shows "Wrapping up...".
@Wesleyleung the solution here is to switch using our SDK's `resumeFromTx` utility, but we are pending there to have all the routes supported. I think starting to move away from the WHScan API for in-progress widget is the right call, because the plan is eventually having Tx History and this functionality on the SDK.

**Comment by tsadovska** [comment]
Issue is no longer reproducible. Correct status is shown in the option. 

![image](https://github.com/user-attachments/assets/187e3876-e220-448c-9dc5-5a98b9d33d1c)

Transactions completed successfully.
* Sent WAVAX from Base (MetaMask) to Scroll (MetaMask), link to [Wormholescan](https://wormholescan.io/#/tx/0x24f45e97210e2b208dd6e3e9224a563368f20daee967e06547e9cd261bba718c)
* Send WAVAX from Base (OKX) to Scroll (OKX), link to [Wormholescan](https://wormholescan.io/#/tx/0x83e950834eb289decb985676bfcd7ccecfe6f9ba12b29cfdd49d60510b39ec5c)
