### ISSUE TITLE
[QA] Pop-up to Approve transaction appears 4 times

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#465]
Preconditions:
1. Send From section connected to Metamask
2. Send To section connected to Phantom

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. Prepare to send 0.003221 MATIC from Mumbai to Solana
2. Click Approve and proceed with transaction
3. Click Claim when option given
4. Observe the pop-up notifications from Phantom wallet to Approve transaction

Actual result: The pop-up to Approve transaction after clicking Claim appeared 4 times.

Expected result: Pop-up appears if Network needs to be changed and to Approve transaction.

Attachment:
https://drive.google.com/file/d/142UyRH-OmsOt8QFz-sNdlHsu9gJ1hopH/view?usp=share_link

<img width="1308" alt="Screenshot 2023-04-28 at 13 43 31" src="https://user-images.githubusercontent.com/91047061/235127652-da6cd097-50cc-4015-a9dc-5de06883863f.png">

**Comment by AigaD** [comment]
Still reproducible, seems that on the pop-ups gas estimates are changed and for that reason 4 pop-ups to confirm the transaction are shown?
Tested from: https://wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/dd94826e-ddaf-448d-9d6b-fe11e089143a

**Comment by tsadovska** [comment]
Issue will be rechecked after https://github.com/wormhole-foundation/wormhole-connect/issues/1757 is resolved.

**Comment by tsadovska** [comment]
Transactions to Solana are successfully completed. Closing as expected behaviour. 
* https://wormhole-connect.netlify.app/ [Testnet]. Checked BNB transfer from [BSC](https://testnet.bscscan.com/tx/0x694314566c8a870e8da4b2e4d455bc119879627b745cf0868aa95a499dd055b6) (MetaMask) to [Solana](https://explorer.solana.com/tx/GKAmp8a5ico9YdDnj8Q1YUg396zjMgY3UiVr3NFxwZXtKJXxSeSEutHM9HYrc3CFDcqCqRmsbBwTHwB1cToLJ8s?cluster=devnet) (Phantom)
* https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. Checked MATIC transfer from [Polygon](https://polygonscan.com/tx/0xa839007edb7553ccba55e243056b32e5037cd448bb166c6499b7a159dc041777) (MetaMask) to [Solana](https://explorer.solana.com/tx/4TFALcqjasp5dCHyrBXkCbZJwm499tJVauLtmFxPqnJ17ChEij8kdL5KzLYjAFWHqiW1RQd8H8g1MHJy3URBhgc6) (Phantom).
