### ISSUE TITLE
Hashflow integration - investigation

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#600]
Investigate and plan Hashflow integration

**Comment by aakashthumaty** [comment]
3 major changes:

- Let users select recipient asset (right now we default recipient asset to be  "wrapped source asset" e.g. Eth -> WETH
- Indicate to user that they CAN choose non wrapped asset i.e. force them to click a dropdown list on the recipient asset side, e.g. for an Eth from Ethereum to Solana transfer, their dropdown should include both WETH AND Sol as options for the recipient asset
- integrate the onchain calls to Hashflow when a user selects a recipient asset/route that implies need to go through Hashflow instead of the token bridge contracts

**Comment by aakashthumaty** [comment]
Designs in Figma

**Comment by anondev2323** [comment]
Notes on the changes between the current state of designs and what is currently implemented. Will break these down into separate issues:

Add network swap button
- Swap wallets also? Or clear wallets if not supported?
Make dest token/amount fields editable
- Disable destination amount if it will be a bridge and not a swap
Transaction history?
Style wallet dropdown
Add USD values
Add asset/balance/USD header to tokens modal
Asset filtering (balance, stablecoins, trending)
USDC warning (You will not get native USDC, you will need to perform a swap on the destination chain)
Routes (This route provided by Hashflow)
Hashflow preview
Send button updates
Slippage? Remove from designs?
Tx Status page for Hashflow
Customization playground
