### ISSUE TITLE
[QA] Cannot register token for multiple transactions

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#648]
Preconditions:
Metamask Wallet is connected at sending From section
Nightly connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
https://646cdfd19fc09113f72e51a0--wormhole-connect.netlify.app/#

We cannot register token for transactions:

1. FTM - Fantom to Aptos
2. GLMR - Moonbase to Aptos
3. SUI - Sui to Aptos

Attachment:

<img width="1214" alt="Screenshot 2023-05-25 at 09 23 33" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2d4b9f72-207f-435c-847b-0a76322c0b7f">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6728c829-2a3b-4939-be14-c9ddf0722e4d

**Comment by AigaD** [comment]
The same behaviour also reproduced for trying to register SUI token for transaction SUI - > Sei
Tested from: https://feature-sei--wormhole-connect.netlify.app/ and https://wormhole-foundation.github.io/example-token-bridge-ui/#/register
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2f9796c1-8391-403f-acb2-46960d59be22

**Comment by aadam-10** [comment]
issue is not reproducible anymore, it must have been a temporary issue with the rpc

**Comment by kev1n-peters** [comment]
There seems to be an issue with creating wrapped tokens in Aptos testnet

**Comment by AigaD** [comment]
Cannot register tokens Fantom and Moonbase (Metamask) for transfer to Aptos (Petra).
Tested from: https://wormhole-connect.netlify.app/ / https://wormhole-foundation.github.io/example-token-bridge-ui/#/register
Attachment:

<img width="1141" alt="Screenshot 2023-06-29 at 09 55 15" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9d1a8c7c-c9ca-4eae-b77a-e3740fc076f3">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/fe0b35c9-9cd4-4057-9159-43056ca3c17a

**Comment by AigaD** [comment]
Cannot register token Moonbase -> Aptos.
Tested from: https://wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/afb1b66a-7901-4777-80d5-c26bddfb5671

**Comment by AigaD** [comment]
Cannot register Sui -> Moonbase SUI token when testing from https://base-relayer--wormhole-connect.netlify.app/#, it directs to https://wormhole-foundation.github.io/example-token-bridge-ui/#/register where an error is shown.
Moonbeam Network is not present at https://testnet.portal-bridge-ui.pages.dev/18c38dbb6a/#/register
Attachment:
<img width="1423" alt="Screenshot 2023-08-21 at 16 34 00" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d3aa8a22-9ec6-4215-9432-6bb4985c6c4d">

**Comment by AigaD** [comment]
Cannot register multiple tokens from: https://cctp-testnet--wormhole-connect.netlify.app/ / https://wormhole-foundation.github.io/example-token-bridge-ui/#/register
In example shown:
Cannot register ETH (Arbitrum Goerli) token for transaction Arbitrum -> BSC
Cannot register AVAX for transaction Fuji -> Arbitrum Goerli

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7fa9b1ca-55e4-471f-97c8-3abd5ececcae

<img width="1401" alt="Screenshot 2023-09-07 at 10 43 30" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/21074e06-3fc7-4d63-ad15-23278551aff6">

**Comment by AigaD** [comment]
Managed to register few assets for transactions to Arbitrum Goerli through https://7a7e292f.portal-bridge-ui.pages.dev/#/transfer , but cannot register assets for transactions from Arbitrum Goerli. Through this link https://7a7e292f.portal-bridge-ui.pages.dev/#/transfer Asset list does not show any available assets for Arbitrum.
Attachment:
<img width="1203" alt="Screenshot 2023-09-11 at 11 52 24" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/fe42a5d9-da63-4892-9768-9318cae36996">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0dc0c881-3c88-43fb-bb57-b0c8c5ef6729

**Comment by AigaD** [comment]
Cannot register ETH token for transaction Goerli-> Aptos from https://feature-configurable-routes--wormhole-connect.netlify.app/#
Attachment:
<img width="1213" alt="Screenshot 2023-09-13 at 12 28 16" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/42d2ce56-06d5-402d-a4e9-e23ecb2b880e">

**Comment by AigaD** [comment]
Cannot register CELO token for transaction Celo-> Aptos from https://latest--wormhole-connect.netlify.app/#
Attachment:
<img width="1244" alt="Screenshot 2023-09-14 at 15 01 59" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/fb2521f7-7f94-4e5f-8efd-cfb83ee4b4e6">
<img width="1409" alt="Screenshot 2023-09-14 at 15 01 44" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5c4ca947-c4fa-4004-afbc-5332d4f3ed88">

**Comment by AigaD** [comment]
cannot register ETH token for TX Arbitrum Goerli -> Solana
Tested from: https://deploy-preview-907--wormhole-connect.netlify.app/
Registered ETH Arbitrum Goerli ( 0xEe01c0CD76354C383B8c7B4e65EA88D00B06f36f ) through https://wormhole-foundation.github.io/example-token-bridge-ui/#/register , but starting the TX again from https://deploy-preview-907--wormhole-connect.netlify.app/ it still shows as not registered

<img width="1198" alt="Screenshot 2023-09-15 at 12 13 37" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f434a7d4-ce98-4507-a3ce-d8ccd4adcb48">

Also SOL from Solana-> Moonbeam

<img width="1277" alt="Screenshot 2023-09-15 at 12 45 09" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/bba6c94d-54f6-40d1-94da-078196c506ba">

<img width="986" alt="Screenshot 2023-09-15 at 12 46 15" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/629a8594-532f-4468-bc46-870036569a08">

**Comment by tsadovska** [comment]
Token is shown as not registered and "Register now" button is displayed on https://wormhole-foundation.github.io/example-token-bridge-ui/#/transfer screen after user has successfully registered the token and clicked on "Return to transfer" button.



https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/d2d31fff-b1bb-4bce-8fb0-3111ea230463

**Comment by tsadovska** [comment]
The same issue occurs when registering USDC (Arbitrum) on Solana. Token is shown as not registered and "Register now" button is displayed on https://wormhole-foundation.github.io/example-token-bridge-ui/#/transfer screen after user has successfully registered the token and clicked on "Return to transfer" button.


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1badcfa7-be4d-487b-9bd0-175e69c8dd98

**Comment by AigaD** [comment]
Cannot register multiple assets (WAVAX/ WMATIC) for transaction from Goerli to Aptos
Tested from: https://deploy-preview-1015--wormhole-connect.netlify.app/#

**Comment by AigaD** [comment]
Cannot register ETH (Optimism) asset for transaction Optimism -> Base
Tested from: https://deploy-preview-1029--wormhole-connect.netlify.app/#
Attachment:
<img width="1059" alt="Screenshot 2023-09-26 at 15 53 59" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ffe75d0a-5832-4bdb-965c-c6a9d926dfbd">

**Comment by AigaD** [comment]
Cannot register SOL asset for transaction Solana -> Aptos
Attachment:
<img width="1125" alt="Screenshot 2023-09-27 at 08 26 12" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a7e948c9-b895-442e-a54d-30139bd755f4">

**Comment by AigaD** [comment]
Issue reproducible, tested from: https://wormhole-connect.netlify.app/#
Attachment:
<img width="1263" alt="Screenshot 2023-10-06 at 09 58 12" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ee251d01-3572-4cce-a7cc-a2c13b2ad3d0">
<img width="1227" alt="Screenshot 2023-10-06 at 09 57 34" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d396d405-fe0e-46db-a8b9-9efd7f00c296">

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/
Cannot register APT asset for transaction Aptos -> Sui
Attachment:
![Screenshot 2023-10-16 at 09 47 33](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d8b673db-3994-4988-8c9d-95c83a724872)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Cannot register USDC (Arbitrum) asset for transaction Arbitrum to Evmos. Evmos is not found in https://www.portalbridge.com/#/register Network list

**Comment by tsadovska** [comment]
Rechecked the mentioned scenarios.

Scenarios that are no longer reproducible:
* Register WFTM on Aptos - Tested OK ([FTMScan](https://testnet.ftmscan.com/tx/0x35ee9bb3e30ed674bdda1a3c98a98fd0daba97183edebdb170d20eecbf92bad7), [Aptos explorer](https://explorer.aptoslabs.com/txn/0x1ed23ccc0e3626f0b4dadab45985ccd1ca56e3b212675ba16825c19a8e324baf?network=testnet))
* Register WGLMR on Aptos - Tested OK ([Moonscan](https://moonbase.moonscan.io/tx/0x59bb54cc6f2d7a61bfe61cc41a2e5143ced47f13f8f5cc8488f4b579a5912e46), [Aptos explorer](https://explorer.aptoslabs.com/txn/0xc128ca9a32ca38e0c86dd28b204b39ea2f6ff31fb9f9bd55b1f10e0cea46a262?network=testnet))

Remaining issues:
* Cannot register WSOL on Moonbase (address: So11111111111111111111111111111111111111112). Error is displayed on Step 3 "Send attestation": `failed to send transaction: Transaction simulation failed: Error processing Instruction 1: custom program error: 0x1870`
* Cannot register USDC (Arbitrum) on Solana - Token registration page shows that token is successfully created, but warning message to register token does not disapper ([Arbiscan](https://goerli.arbiscan.io/tx/0xfb8da636b17bd5ab9fe328092eb72cdc33a522431baf4ed4954aeefab5e04ba9), [Solscan](https://solscan.io/tx/3zUiAAscyTp47L6MyGnBeDeRoU8favYYRTJsczF4T3HWKJ45gTekY3b77EjsbawYWsvJhyCxKJ3wRV5B8s99APuy?cluster=devnet)). 
* Cannot register Base (ETH) on Optimism (Goerli). Error is displayed on Step 3 "Send attestation":

`cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction {"from":"0x0a370E7c5F7F944d451B48bc151a7BEC454bc185","to":"0x23908A62110e21C04F3A4e011d24F901F911744A","data":"0xc48fa11500000000000000000000000042000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000059110000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":-32000,"message":"execution reverted"},"stack":"{\n \"code\": -32603,\n \"message\": \"Internal JSON-RPC error.\",\n \"data\": {\n \"code\": -32000,\n \"message\": \"execution reverted\"\n },\n \"stack\": \"Error: Internal JSON-RPC error.\\n at i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:10940)\\n at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:13880)\\n at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:14490)\\n at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:44665)\\n at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:45664\\n at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:37935\"\n}\n at i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:10940)\n at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:13880)\n at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:14490)\n at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:44665)\n at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:45664\n at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:37935"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
`
* Cannot register APT on Kujira, because Kujira network is not available on [Portal Bridge](https://wormhole-foundation.github.io/example-token-bridge-ui/#/register)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect-mainnet.netlify.app/ then redirected to Portal Bridge token registration - https://www.portalbridge.com/#/register
Cannot register USDC token for transaction Base to Aptos
Attachment:
![Screenshot 2023-10-26 at 13 31 25](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/29d72955-3c48-4ac3-8a9b-9b3ce20e3da5)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2bb6b6e0-2198-407d-b18d-3bffa76be9a7


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4823f5a8-4bb4-4451-91a1-685318aff2c3

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/# and https://wormhole-foundation.github.io/example-token-bridge-ui/#/register
Cannot register USDC (Goerli) token for transaction Solana (Solflare) to Aptos (Martian)
Attachment:

<img width="1262" alt="Screenshot 2023-11-01 at 14 04 31" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/895ca430-b13b-4981-96cf-fccf8e03f27e">

**Comment by tsadovska** [comment]
Cannot register SEI on Cosmoshub, because Cosmoshub network is not available in the list https://wormhole-foundation.github.io/example-token-bridge-ui/#/register. 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/da08988a-54fe-4e01-8b98-0726fdf88f02)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/4313179c-734f-47e4-943c-9811751de182)

**Comment by tsadovska** [comment]
Cannot register USDC (Base) for transaction from Base (Metamask) to Aptos (Spika). Asset contract: 0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913. Error "Wallet is not connected to Mainnet" is shown in Step 4 "Create wrapped token" when wallet is connected to correct network. Error does not disappear after disconnecting and reconnecting wallet again. 

Link to [BaseScan](https://basescan.org/tx/0x21c31656d6b9ba5bc56a0d2935785a4a7509c60cff55763ee79e530e331a2863)
Link to [Wormhole scan](https://wormholescan.io/#/tx/0x21c31656d6b9ba5bc56a0d2935785a4a7509c60cff55763ee79e530e331a2863?network=MAINNET)

![Screenshot 2023-11-07 at 14 08 43](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/03a05539-8281-418f-8d0e-d079dcf988ab)


![Screenshot 2023-11-07 at 14 12 59](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/4a762419-c12f-4a37-b409-2b800a87444b)

**Comment by tsadovska** [comment]
Cannot register tBTC for transaction from Solana (Phantom) to Sei (Leap). Asset contract: 6DNSN2BJsaPFdFFc1zP37kkeNe4Usc1Sqkzr9C9vPWcU. Error "failed to send transaction: Transaction simulation failed: Error processing Instruction 1: custom program error: 0x1870" is shown in Step 3 "Send Attestation". 

Link to [Solscan](https://solscan.io/token/6DNSN2BJsaPFdFFc1zP37kkeNe4Usc1Sqkzr9C9vPWcU?cluster=devnet)

Error:
```
Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 1: custom program error: 0x1870
    at ni.sendEncodedTransaction (connection.ts:5054:13)
    at async ni.sendRawTransaction (connection.ts:5017:5)
    at async ien (solana.ts:20:9)
    at async useHandleAttest.tsx:367:11
```

![Screenshot 2023-11-10 at 15 15 03](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/8f161e31-6e46-49d1-ac6d-781652524ebc)

**Comment by AigaD** [comment]
Tested from: https://deploy-preview-1174--wormhole-connect-mainnet.netlify.app/# and https://www.portalbridge.com/#/register
[Wormholescan](https://wormholescan.io/#/tx/0x9cd413827627bb263ed61a63aabc118a8e41bb4631e8f9d34c1dcf82bce21183?network=MAINNET)
[Explorer](https://explorer.celo.org/mainnet/tx/0xc1857f59fb405fd5d593e3b8c6cd34ffc243f22b8e8145aea6133abe6faa21cb)
Token shows as registered, but when returning to Wormhole-connect transaction, it still shows as not registered.
tBTC (Arbitrum) Contract address used - 0x6c84a8f1c29108F47a79964b5Fe888D4f4D0dE40 

Attachment:

![Screenshot 2023-11-14 at 13 01 06](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5d7a4f02-718a-4539-b1d2-c6637eadb7f5)

![Screenshot 2023-11-14 at 13 08 58](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4690929e-6b8f-4914-a25f-4f849649c4a0)

**Comment by tsadovska** [comment]
Cannot register tBTC for transaction from Polygon (Metamask) to Aptos (Spika). Asset contract: 0x236aa50979d5f3de3bd1eeb40e81137f22ab794b. Error "Wallet is not connected to Mainnet" is shown in Step 4 "Create wrapped token" when wallet is connected to correct network. Error does not disappear after disconnecting and reconnecting wallet again.

![Screenshot 2023-11-15 at 20 16 42](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/99441f6b-3e9a-4add-a79f-e915e72c3c67)

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1174--wormhole-connect.netlify.app/#
Cannot register SEI asset for transaction Moonbase to Osmosis, as Osmosis Network is not present in the Network list on https://wormhole-foundation.github.io/example-token-bridge-ui/#/register
Attachment:
![Screenshot 2023-11-16 at 13 05 26](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f0f39955-405e-46c2-8135-fcb1267bc183)

**Comment by tsadovska** [comment]
Rechecked scenarios that are mentioned in the ticket. 

Mainnet assets
<google-sheets-html-origin>
CHAINS | ASSET | RESULT
-- | -- | --
Fantom -> Aptos | FTM | already registered
Sui -> Aptos | SUI | already registered
Celo -> Aptos | CELO | already registered
Fantom -> Moonbeam | FTM | already registered
Sui -> Moonbeam | SUI | already registered
Optimism -> Base | ETH (Optimism) | already registered
Arbitrum -> Celo | tBTC | #1247

Testnet assets
<google-sheets-html-origin>
CHAINS | ASSET | RESULT
-- | -- | --
Goerli -> Aptos | ETH | already registered
Moonbase -> Aptos | GLMR | already registered
Goerli -> Aptos | WAVAX | already registered
Goerli -> Aptos | WMATIC | already registered
Solana -> Aptos | SOL | already registered
Arbitrum Goerli -> BSC | ETH (Arbitrum) | No bridge or swap route available for selected tokens
Fuji -> Arbitrum Goerli | AVAX | already registered
Arbitrum Goerli -> Solana | ETH | No bridge or swap route available for selected tokens
Arbitrum Goerli -> Solana | USDC | #1245
Base -> Solana | USDC | #1243
Solana -> Moonbase | SOL | #1237
Arbitrum Goerli -> Optimism Goerli | ETH (Base Goerli) | No bridge or swap route available for selected tokens
Aptos -> Sui | APT (Aptos) | already registered
Arbitrum -> Evmos | USDC (Arbitrum) | already registered
Base -> Optimism Goerli | Base ETH | already registered
Base -> Aptos | USDC | already registered
Solana -> Aptos | USDC | already registered
Solana -> Sei | tBTC | #1246
Sei -> Evmos/ Kujira/ Cosmoshub/ Osmosis | SEI | #1238



Ticket is closed.
