### ISSUE TITLE
[QA] BitKeep wallet is opened when user clicks on Petra option

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#717]
#### Build:
https://wormhole-connect.netlify.app/  [Testnet] 

#### Preconditions:
“BitKeep: Crypto & NFT Wallet” and “Petra Aptos Wallet​​” extensions are installed.

#### Steps:

1. Click “Connect wallet” button
2. Click “Petra” option

#### Actual result:
BitKeep wallet is opened.

#### Expected result:
Petra wallet is opened.

#### Note:
User is able to connect BitKeep wallet when “BitKeep: Crypto & NFT Wallet” is disabled. 

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 114.0.5735.106 (Official Build) (x86_64)

#### Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/8fae1885-4ca2-408b-b33f-8e3c9b0e3a38

**Comment by AigaD** [comment]
Issue reproduced on Mainnet - https://mainnet--wormhole-connect.netlify.app/# using these steps:
1. Click on Connect Wallet
2. Find Phantom wallet
3. Click on it
4. Observe
Actual result: BitKeep wallet notification is opened instead of Phantom
Expected result: Phantom wallet window is opened.

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ae45d830-de06-4bed-9e9f-1579d2e1687a

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet] and https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. Correct wallet opens after user selects it.
