### ISSUE TITLE
[QA] Compass and Fin wallets are not shown in the list if network is selected first

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#842]
## Describe the current behavior in detail
Compass and Fin wallets are not shown in the list of wallets on "Connect wallet" screen if Osmosis network is selected first. 

Builds - Tested NOK:
https://feat-cosmos-gateways--wormhole-connect.netlify.app/ [Testnet]
https://feat-cosmos-gateways-mainnet--wormhole-connect.netlify.app/ [Mainnet]

Checked on macOS Monterey 12.6.7 with Chrome Version 116.0.5845.110 (Official Build) (x86_64).

Steps:
1. Click "Connect wallet" button
2. Observe available Cosmos wallets (Actual result: Compass, Fin, Falcon, Coin98, Leap, Keplr)
3. Close window
4. Select Osmosis network in "From" section
5. Click "Connect wallet" button
6. Observe available Cosmos wallets (Actual result: Coin98, Falcon, Leap, Keplr)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/125b103c-2756-4d91-9509-c1dcde0c4e73

 
## What is the expected/desired behavior
Compass, Fin, Falcon, Coin98, Leap, Keplr wallets are shown in the list when Osmosis network is selected first.

**Comment by AigaD** [comment]
Linking to this issue: https://github.com/wormhole-foundation/wormhole-connect/issues/1016 because in current behaviour Cosmos wallets are not shown in the Connect Wallet list until Network is selected.
Tested from: https://wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3cc758d7-d6a3-4768-87a0-372b959657ea

**Comment by AigaD** [comment]
Closing this and linking to this issue: https://github.com/wormhole-foundation/wormhole-connect/issues/1016 because in current behaviour Cosmos wallets are not shown in the Connect Wallet list until Network is selected.
Tested from: https://wormhole-connect.netlify.app/# and https://wormhole-connect-mainnet.netlify.app/
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3cc758d7-d6a3-4768-87a0-372b959657ea

**Comment by AigaD** [comment]
Re-opening the issue.
Current behaviour shows all Cosmos wallets before Network is selected. Fin and Compass wallets are no longer shown in the list after Osmosis/Evmos network is selected
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5f060c35-a069-4173-bb50-258ae474b622

**Comment by M-Picco** [comment]
Compass and Fin are specific for Sei, they shouldn't show for Cosmos chains. PR #1144 fixes the wallets shown for Cosmos chains when no chain is selected. It seems I forgot to link the issue at the time.
